name: Automated Daily Commit

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC (7:30 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This allows GitHub Actions to push changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure authentication

      - name: Modify or Create File
        run: |
          echo "Last updated on $(date)" > last_update.txt
          cat last_update.txt  # Debugging step to verify file creation

      - name: Verify File Exists
        run: |
          ls -la
          cat last_update.txt || echo "File not found!"

      - name: Commit and Push Changes (22f3001952@ds.study.iitm.ac.in)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22f3001952@ds.study.iitm.ac.in"

          git add last_update.txt
          git commit -m "Automated daily commit $(date)" || echo "No changes to commit"

          # Authenticate using GitHub Token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/anshul49yadav/TDS_GA4Q8.git main
