name: Automated Daily Commit

on:
  schedule:
    - cron: '19 2 * * *'  # Runs daily at 2:19 AM UTC (7:49 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to push commits
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure authentication

      - name: Modify or Create File
        run: |
          echo "Last updated on $(date)" > last_update.txt
          cat last_update.txt  # Debugging step

      - name: Verify File Exists
        run: |
          ls -la
          cat last_update.txt || echo "File not found!"

      - name: Commit and Push Changes (22f3001952@ds.study.iitm.ac.in)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22f3001952@ds.study.iitm.ac.in"

          git add last_update.txt
          
          # Force a commit even if nothing changes
          git commit -m "Automated daily commit $(date)" || true
          
          # Push with authentication
          git push origin main
